### ISSUE TITLE
(ArgumentError) struct fields definition must be list, got: nil

### ISSUE THREAD

**Issue by fschuindt** [b2beauty/iugu-elixir#3]
## Problem

It's using an older version of httpoison, which conflicts with the service's umbrella dependency tree:
```
$ mix deps.get                                                                     

* Updating iugu (https://github.com/b2beauty/iugu-elixir.git)
Resolving Hex dependencies...

Failed to use "httpoison" (version 0.13.0) because
  deps/beautydate_api/mix.exs requires ~> 1.0
  deps/iugu/mix.exs requires ~> 0.13

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

So I updated it in the branch `upgrade/httpoison_1.0` and used it: `{:iugu, github: "b2beauty/iugu-elixir", branch: "upgrade/httpoison_1.0"}`

The `mix deps.gets` finished just fine, but `iex -S mix run` returns this:
```
$ iex -S mix run

Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

==> iugu
Compiling 7 files (.ex)

== Compilation error in file lib/resources/customer.ex ==
** (ArgumentError) struct fields definition must be list, got: nil
    (elixir) lib/kernel/utils.ex:73: Kernel.Utils.defstruct/2
    lib/resources/customer.ex:6: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
could not compile dependency :iugu, "mix compile" failed. You can recompile this dependency with "mix deps.compile iugu", update it with "mix deps.update iugu" or clean it with "mix deps.clean iugu"
```

Any tip?

**Comment by tiagopog** [comment]
I couldn't  manage to reproduce the error you've got at compile time. As you can see in the following log, after updating the `httpoison` dependency it kept working like a charm: 

```sh
$ docker run --rm -it -v $(pwd):/home iugu-elixir bash

root@ab60dc4dbaf0:/home# mix compile
Unchecked dependencies for environment dev:
* hackney (Hex package)
  lock mismatch: the dependency is out of date. To fetch locked version run "mix deps.get"
* httpoison (Hex package)
  lock mismatch: the dependency is out of date. To fetch locked version run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies

root@ab60dc4dbaf0:/home# mix do deps.get, deps.compile
Resolving Hex dependencies...
Dependency resolution completed:
  certifi 2.0.0
  dialyxir 0.5.1
  hackney 1.11.0
  httpoison 1.0.0
  idna 5.1.0
  metrics 1.0.1
  mimerl 1.0.2
  poison 3.1.0
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.3.1
* Updating httpoison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/httpoison-1.0.0.tar)
  Fetched package
* Updating hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.11.0.tar)
  Fetched package
Could not find "rebar3", which is needed to build dependency :mimerl
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] Y
* creating /root/.mix/rebar
* creating /root/.mix/rebar3
===> Compiling mimerl
===> Compiling metrics
===> Compiling unicode_util_compat
===> Package unicode_util_compat-0.3.1 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /root/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /root/.cache/rebar3/hex/default/packages.idx
===> Compiling idna
warning: String.strip/1 is deprecated, use String.trim/1
  /home/deps/poison/mix.exs:4

==> ssl_verify_fun (compile)
==> dialyxir
Generated dialyxir app
===> Compiling certifi
===> Compiling hackney
==> httpoison
Compiling 2 files (.ex)
Generated httpoison app

root@ab60dc4dbaf0:/home# iex -S mix
Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]
Compiling 7 files (.ex)
Generated iugu app
Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> %Iugu.Request{}
%Iugu.Request{api_key: nil, api_token: nil, api_version: "v1", body: "",
 domain: "https://api.iugu.com", params: %{}, path: ""}

iex(2)> Iugu.Customer.list()
{:ok,
 [%Iugu.Customer{cc_emails: nil, city: nil, complement: nil,
   cpf_cnpj: "99384620220", created_at: "2018-03-23T23:42:27-03:00",
   custom_variables: [%{"name" => "business.id",
      "value" => "092fa7a9-02bc-4e78-80b7-70d92960fdd1"}],
   default_payment_method_id: nil, district: nil,
   email: "foobar777@beautydate.com", id: "54A5FE8FA367464FB6575693D14392FC",
   name: "Foobar 777", notes: nil, number: nil,
   proxy_payments_from_customer_id: nil, state: nil, street: nil,
   updated_at: "2018-03-23T23:42:27-03:00", zip_code: nil},
...
```

 Have you tried running the commands suggested by the compiler?

> You can recompile this dependency with "mix deps.compile iugu", update it with "mix deps.update iugu" or clean it with "mix deps.clean iugu"

Maybe there are cached binaries or something interfering with the compilation, then running them should do the trick. Anyway, it's not clear to me what is actually happening.

**Comment by fschuindt** [comment]
Hm, looks tricky. I'm able to compile it by itself. But when added as a dep into one of my umbrella apps (the `:iugu_publisher`), this error appears.

I tried all the suggestions. I even managed to compile your app using Elixir 1.6, you are using 1.3 and the umbrella stack uses 1.6 so I thought it might represent some issue. I don't know.

I'm researching on it right now.

Edit: Just adding, I did it all after cleaning the `deps/` and `_build/` directories. So it was all downloaded and compiled at time.

**Comment by fschuindt** [comment]
Better steps to reproduce:

+ Erlang `Erlang/OTP 20 [erts-9.2.1]`
+ Elixir `Elixir 1.6.3 (compiled with OTP 20)`
+ Mix `Mix 1.6.3 (compiled with OTP 20)`

**Comment by fschuindt** [comment]
Better steps to reproduce:

+ Erlang `Erlang/OTP 20 [erts-9.2.1]`
+ Elixir `Elixir 1.6.3 (compiled with OTP 20)`
+ Mix `Mix 1.6.3 (compiled with OTP 20)`

## 1. Create a new Mix application:
```
$ mix new myapp
```

## 2. Add `:iugu` as a dependency
Edit the `mix.exs` file `deps`:
```elixir
  defp deps do
    [
      {:iugu, github: "b2beauty/iugu-elixir", branch: "master"}
    ]
  end
```

## 3. Download it
```
$ mix deps.get
```

## 4. Compile it
```
$ mix compile
==> iugu
Compiling 7 files (.ex)

== Compilation error in file lib/resources/subscription.ex ==
** (ArgumentError) struct fields definition must be list, got: nil
    (elixir) lib/kernel/utils.ex:73: Kernel.Utils.defstruct/2
    lib/resources/subscription.ex:6: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
could not compile dependency :iugu, "mix compile" failed. You can recompile this dependency with "mix deps.compile iugu", update it with "mix deps.update iugu" or clean it with "mix deps.clean iugu"
```

I'm starting to think it's probably a version mismatch somewhere in the code.
Can you try to achieve the same versions as I do?

**Comment by tiagopog** [comment]
Thanks for the detailed the steps, @fschuindt. After a couple of tries I could finally reproduce and check that the source of the problem is related to how the lib was dealing with the config files.

I thought the lib's config setup would be kept across the parent application but [that's not true](https://stackoverflow.com/a/36792072):
> This is expected behavior. Parent project (your phoenix app) is not using configuration from deps. If dependencies require configuration you need to specify it in the parent app, so you would need to copy (...)

Knowing that, then I refactored some points of the `Iugu.{Request,Resource}` modules in order to properly use the config values (or default values in case the former are not set).

Can you please test the update from the [fix branch](https://github.com/b2beauty/iugu-elixir/tree/improvements/base-resources) and give me a feedback? The only thing you should do so it can work is:

1. Update the dependency from this branch:

```elixir
defp deps do
  [
    {:iugu, github: "b2beauty/iugu-elixir", branch: "improvements/base-resources"}
    #...
  ]
end
```

2. Set the `api_key` in the `config/config.exs` file:

```elixir
config :iugu,
  api_key: "foobar"
```

or

```elixir
config :iugu,
  api_key: System.get_env("IUGU_API_KEY")
```

3. Get and compile the dependency:

```
mix do deps.clean iugu, deps.get iugu, deps.compile iugu
```

As the `api_key` you set in your app gets statically compiled with the lib's binary code, in case you need to reset that value you should run those mix tasks again. There might be another way to update the dependency's binary with the config values but I don't know so far (and if you know, please let me know).

**Comment by fschuindt** [comment]
Wonderful.
Compilation is working just fine.

Also thank you for the bonus upgrades, really appreciated.

**Comment by tiagopog** [comment]
Hey, thanks.

After reading an [insightful topic](https://elixirforum.com/t/how-to-access-config-key-in-package/1201) about config keys and dependencies, I've changed the way the lib deals with the Iugu's API key. It no longer compiles the key along with the `%Iugu.Request{}` struct, accessing the parent app's compiled config at runtime rather.

Having that said, now it's all about changing the `config.exs` on your app with no need for dependency recompilation.
