### ISSUE TITLE
Missing "plan_identifier" key in Subscription resource?

### ISSUE THREAD

**Issue by fschuindt** [b2beauty/iugu-elixir#4]
I am not really sure if it's indeed a Subscription field. But the Iugu API docs suggests so.

What do you think? I'm trying to use it.

**Comment by fschuindt** [comment]
cc/ @tiagopog

**Comment by tiagopog** [comment]
You're right, currently it's a missing field in the `Iugu.Subscription` struct. I'm gonna add it.

**Comment by tiagopog** [comment]
Closed by https://github.com/beautydate/iugu-elixir/commit/0f3ccc80a002aecd73a61a35959d4414ade6a45b
